learning_log/learning_log/urls.py
# from django.contrib.staticfiles.urls import staticfiles_urlpatterns
# from django.contrib import staticfiles



from django.contrib import admin
from django.urls import path,include

urlpatterns = [
    path('admin/', admin.site.urls),
    path("",include("learning_logs.urls")),
    
    path("users/", include("users.urls")),

]



#设置静态文件路径
#urlpatterns += staticfiles_urlpatterns()

learning_log/learning_logs/urls.py
#定义learning_logs的URL模式
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
from django.contrib import staticfiles

from django.urls import path, re_path
from . import views
from django.conf.urls.static import static
from django.conf import settings


app_name='learning_logs'


urlpatterns = [
    # 主页
    #代码(?P<topic_id>\d+)捕获一个数字值并将其存储在topic_id中
    path("", views.index, name="index"),
    path("topics/", views.topics, name="topics"),
	#path("videos/", views.videos, name="videos"),
    path("topics/(?P<topic_id>\d+)/", views.topic, name="topic"),
    
    path("new_topic/", views.new_topic, name="new_topic"),

    path("new_entry/(?P<topic_id>\d+)/", views.new_entry, name="new_entry"),
    
    path("edit_entry/<int:entry_id>/", views.edit_entry, name="edit_entry"),
    #path("super/", views.map, name="map"),
    path("shop", views.shop, name="shop"),
    path("confirmation", views.confirmation, name="confirmation"),


    #测试ajax用
    path('update', views.update, name="update"),
    path('data_fresh/', views.data_fresh, name="data_fresh"),
    path("data/<int:id>/",views.data, name="data"),




    #
    # 通过构造的url传递数据，其url接口形式如下： http://127.0.0.1:8000/deal_data/?type=china&comment=niurou&price=5&amount=7
    # 在读取数据的时候，采用方法，p1 = request.GET.get('p1')，即可得到p1的数据
    path("deal_data/",views.deal_data, name="deal_data"),
    path("shou_yin/",views.shou_yin, name="shou_yin"),
    path("jiesuan/",views.jiesuan, name="jiesuan"),
]

#设置静态文件路径
urlpatterns += staticfiles_urlpatterns()

learning_log/users/urls.py
# from django.contrib.staticfiles.urls import staticfiles_urlpatterns
# from django.contrib import staticfiles


from django.contrib.auth.views import LoginView
from django.urls import path
from . import views
app_name = "users"
urlpatterns = [
  path('login/', LoginView.as_view(template_name='users/login.html'), name="login"),
  path('logout/', views.logout_view, name="logout"),
  path("register/", views.register, name="register"),
]

#设置静态文件路径
#urlpatterns += staticfiles_urlpatterns()

learning_log/learning_logs/models.py
from django.db import models

from django.contrib import admin


from django.contrib.auth.models import User

# Create your models here.
'''

#CharField表示由字符和文本组成的数据，参数为预留数据空间。
    #text主要用来存储数据
    DateTimeField用于记录时间和日期，
    auto_now_add=True表示创建新主题时，Django自动将这个属性设为当前日期和时间
    熟悉模型使用字段，参考https://docs.djangoproject.com/en/1.8/ref/models/fields/
'''


class Topic(models.Model):
    """用户学习的主题"""
    text = models.CharField(max_length=200)
    date_added = models.DateTimeField(auto_now_add=True)
    owner = models.ForeignKey(User, on_delete=models.CASCADE)
    def __str__(self):
        """返回模型的字符串表示"""
        return self.text

class Entry(models.Model):
    """学到的有关某个主题的具体知识"""
    # 由于和“主题”是多对一的关系，所以“主题”是“条目”的外键
    topic = models.ForeignKey(Topic, on_delete=models.CASCADE)
    text = models.TextField()
    date_added = models.DateTimeField(auto_now_add=True)

    class Meta:
        verbose_name_plural = "entries"

    def __str__(self):
        """返回模型的字符串表示"""
        # 由于条目包含的文本可能很长，只显示前50个字符
        return self.text[:50] + "..."

		
#上传图片的模型类，name需要在执行数据库迁移时候选择1，进行创建，输入  ‘name’  即可		
class Img(models.Model):
    img = models.ImageField(upload_to='media')
    name =models.CharField(max_length=20)
    date_added = models.DateTimeField(auto_now_add=True)
    
    #def __str__(self):
        #return self.pic



learning_log/learning_logs/forms.py
from django import forms
from .models import Topic, Entry

class TopicForm(forms.ModelForm):
    class Meta:#告诉django根据那个模型创建表单，以及在表单中包含哪些字段
        model =Topic#创建表单
        fields=['text']
        labels={'text':''}#不为该字段生成标签
        
class EntryForm(forms.ModelForm):
    class Meta:
        
        model =Entry
        fields=['text']
        labels={'text':''}#不为该字段生成标签
        widgets={'text':forms.Textarea(attrs={'cols':80})}
        #表单元素，如单行文本框或多行文本区域P387

learning_log/learning_logs/views.py
from django.shortcuts import render,render_to_response

from django.http import HttpResponseRedirect
from django.urls import reverse
from django.conf import settings
from .models import Topic, Entry, Img
from .forms import TopicForm, EntryForm
from django.contrib.auth.decorators import login_required
from django.http import HttpResponseRedirect, Http404,HttpResponse
from django.http import JsonResponse

from django.views.decorators.csrf import csrf_exempt
import json
import time


# Create your views here.
'''该工程主要用于，跳转到url匹配成功的视图函数
试图函数收集数据，并在一定条件下跳转到相应的模板'''

a = [{'type': "笔记本", 'money': 3.5, 'number': 2},
     {'type': "苹果", 'money': 233.3, 'number': 1},{'type': "心相印抽纸", 'money': 2.5, 'number': 1}]


# rlist = [['123456789', '', 5, 2], ['Mike', 'English', 788, 3], ['Bob', 'Math', 4, 5], ['Frank', 'Art', 8, 9],['123456789', '优质牛肉', 5, 2]]
rlist=[]
rlist3=[]


def index(request):
    #学习笔记的主页
    return render(request,'learning_logs/index.html')

@login_required
def topics(request):
    
    """显示所有的主题"""

   
    topics = Topic.objects.order_by('date_added')# 一个上下文字典，传递给模板
    context = {'topics': topics}
    return render(request, 'learning_logs/topics.html',context)

@login_required
def topic(request,topic_id):
    """显示单个主题及其所有条目"""
    topic=Topic.objects.get(id=topic_id)
    imgs=Img.objects.all()
    #for i in imgs:
        #print(i.date_added)
# 确认请求的主题属于当前用户
    #if topic.owner != request.user:
        #raise Http404
    entries=topic.entry_set.order_by('-date_added')
    context = {'topic': topic,'entries': entries,'imgs':imgs,}
    return render(request, 'learning_logs/topic.html',context)

#显示空表单，读取用户输入的表单数据，并将用户重定向到topics

@login_required
def new_topic(request):
    """添加新主题"""
    if request.method !='POST':
        #未提交数据，创建一个新表单
        form=TopicForm()
    else:
        #
        form=TopicForm(request.POST)
        if form.is_valid():
            
 # 添加新主题时关联到特定用户
            new_topic = form.save(commit=False)
            new_topic.owner = request.user
            new_topic.save()
            # 该类将用户重定向到网页topics，函数reverse()根据指定的URL模型确定URL
            return HttpResponseRedirect(reverse('learning_logs:topics'))

    context={'form':form}
    return render(request,'learning_logs/new_topic.html',context)


@login_required
def new_entry(request, topic_id):
    """在特定的主题中添加条目"""

    topic=Topic.objects.get(id=topic_id)
    #提交条目的同时，可以插入图片，实现图片上传
    f1=request.FILES.get('img')
    if request.method == 'POST':
        #如果当前有图片的上传将其存储到本地静态文件中的media中，保证无图片上传时，不影响文本的上传
        if  f1:        
            img = Img(img=request.FILES.get('img'),
                      name=request.FILES.get('img').name,
                      )
            #下面红褐色的为方法二，进行图片上传保存
            #img.pic = settings.MEDIA_ROOT+ f1.name
            img.save()
            
            #fname=settings.MEDIA_ROOT+ f1.name          
            #with open(fname,'wb') as pic:
                #for c in f1.chunks():
                    #pic.write(c)
                   

    if request.method !='POST':
        #未提交数据，创建一个新表单
        form=EntryForm()
        
    else:
        #POST提交的数据，对其进行处理
        form=EntryForm(data=request.POST)
        
# 检查是否填写了所有必不可少的字段。(是否有效)
        if form.is_valid():
            new_entry=form.save(commit=False)
            new_entry.topic=topic
            new_entry.save()
            return HttpResponseRedirect(reverse('learning_logs:topic',
                                                kwargs={'topic_id':topic_id}))
    #先用reverse来获取名称为topic的页面的url，并提供其所需的所有参数，来满足url的生成
    context={'topic':topic,'form':form}
    #参数传递错误
    return render(request,'learning_logs/new_entry.html',context)

@login_required        
def edit_entry(request, entry_id):
    #编辑既有的条目
    entry=Entry.objects.get(id=entry_id)
    topic=entry.topic
    if topic.owner != request.user:
        raise Http404
    if request.method != "POST":
        form=EntryForm(instance=entry)
    else:
        form = EntryForm(instance=entry, data=request.POST)
        if form.is_valid():
            form.save()
            return HttpResponseRedirect(reverse('learning_logs:topic',args=[topic.id]))        
    context={'entry':entry, 'topic':topic, 'form':form}
    return render(request,'learning_logs/edit_entry.html',context)




# #视频还未添加，此处还需要更改
# @login_required
# def videos(request, entry_id):
#     if video.owner != request.user:
#         raise Http404
#     else:
#         videos_list#查看对应文件目录，读取各个视频文件名称，存入列表
#         if videos_list:#视频文件存在
#             #调用人脸识别函数，进行视频处理提取视频中的人物图像
#             #保存人脸图像到服务器对应文件目录，使用数据库记录当前文件的名称，路径
#             #进行人脸图像展示，传递图像路径和文件名称列表到模板
#             return rebder(request,'learning_logs/vieos_pictures.html',context)




#重定向到对应的页面


@login_required
def shop(request):

    # """添加新的商品"""
    # if request.method != 'POST':
    #     # 未提交数据，创建一个新表单
    #     form = TopicForm()
    # else:
    #     #
    #     form = TopicForm(request.POST)
    #     if form.is_valid():
    #         # 添加新主题时关联到特定用户
    #         new_shop = form.save(commit=False)
    #         new_shop.owner = request.users
    #         new_shop.save()
    #         # 该类将用户重定向到网页topics，函数reverse()根据指定的URL模型确定URL
    #         return HttpResponseRedirect(reverse('learning_logs:topics'))


    return render(request, 'learning_logs/shop.html',{'type': a})

@login_required
def confirmation(request):
    return render(request, 'learning_logs/confirmation.html')

#此实例中未用到
@login_required  
def uploadImg(request): # 图片上传函数
    if request.method == 'POST':
        img = Img(img_url=request.FILES.get('img'))
        img.save()
    return render(request, 'learning_logs/new_entry.html')


        
    


@csrf_exempt
def data_fresh(request):

    context = {"data1":8
               }
    if time.sleep(10):
        context.update(data2=89)
        print(context)

    return JsonResponse(context)


sa=0
ind=0


def data(request,id):
    global rlist, rlist3, sa,ind
    aa=len(rlist)
    da=len(rlist3)
    #u = 0
    t = 0
    #此处问题为，当原始没有数据的时候，后面虽然有数据到来，但随着id的增加永远大于a
    #解决方法，使得test中的id不增加，每次使用完rlist的数据，将其清空，判断其是否长度为0，不为0，则进行添加，为零执行下面的else语句

    #   将rlist[int(id)][3]，中的id值改为0即可，不用管 test中i++带来的影响

    if aa ==1:
        rlist2 = []

        # 判断数据是否一样
        if da == 0:
            rlist3.append({"type": rlist[0][0], "amount": rlist[0][3], "id":id})   #rlist[int(id)][0]
            sa=0
        else:

            for item in rlist3:

                if item['type']==rlist[0][0]:
                    rlist[0][3]=item["amount"]+rlist[0][3]
                    item["amount"]=rlist[0][3]
                    print('相同的时候数量为：',rlist[0][3])
                    sa = 1
                    ind=item["id"]
                    t=1

            if t ==0:
                rlist3.append({"type": rlist[0][0], "amount": rlist[0][3], "id":id})
                sa=0

        rlist2.append({"type" : rlist[0][0], "comment" : rlist[0][1],"price":rlist[0][2],"amount":rlist[0][3],"sa": sa ,"ind":ind})
        rjson = json.dumps(rlist2)
        response = HttpResponse()
        response['Content-Type'] = "text/javascript"
        response.write(rjson)
        rlist=[]
        return response
    else:
        b=[{"type" :'',"comment" :'',"price":'',"amount":'',"sa":'',"ind":''}]
        rjson = json.dumps(b)
        response = HttpResponse()
        response['Content-Type'] = "text/javascript"
        response.write(rjson)
        return response


def update(request):

    return render_to_response('learning_logs/test.html')


def deal_data(request):
    global rlist
    typ = request.GET.get('type')
    comment = request.GET.get('comment')
    price= request.GET.get('price')
    amount= request.GET.get('amount')
    rlist.append([typ, comment,eval(price),eval(amount)])
    print(type(eval(price)))
    return HttpResponse("p1 = " + typ+ "; p2 = " + comment)

k=0
def shou_yin(request):
    global k
    k=1
    return HttpResponse("<p1>请您出示收款码</p1>")

def jiesuan(request):
    global k
    return HttpResponse(k)








        


   

learning_log/learning_logs/templates/learning_logs/base.html
{% load bootstrap3 %}
<!DOCTYPE html>

<html lang="en">

<head>

  <meta charset="UTF-8">

  <meta http-equiv="x-ua-compatible" content="IE=edge">

  <meta name="viewport" content="width=device-width, initial-scale=1">


  <title>Share your resource</title>


  {% bootstrap_css %}

  {% bootstrap_javascript %}

</head>


<body>
<!-- Static navbar -->
<nav class="navbar navbar-default navbar-static-top">
  <div class="container">

    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" 
              data-target="#navbar" aria-expanded="false" aria-controls="navbar">
      </button>
      <a class="navbar-brand" href="{% url 'learning_logs:index' %}">Learning Log</a>
    </div>

    <div id="navbar" class="navbar-collapse collapse">
      <ul class="nav navbar-nav">
        <li><a href="{% url 'learning_logs:topics' %}">Topics</a></li>
		<li><a href="{% url 'learning_logs:shop' %}">购物车页面</a></li>
        <li><a href="{% url 'learning_logs:update' %}">超市收银系统</a></li>

      </ul>

      <ul class="nav navbar-nav navbar-right">
        {% if user.is_authenticated %}
          <li><a>Hello, {{ user.username }}.</a></li>
          <li><a href="{% url 'users:logout' %}">log out</a></li>
        {% else %}
          <li><a href="{% url 'users:register' %}">register</a></li>
          <li><a href="{% url 'users:login' %}">log in</a></li>
        {% endif %}
      </ul>
    </div><!--/.nav-collapse -->

  </div>
</nav>

<div class="container">

  <div class="page-header">
    {% block header %}{% endblock %}
  </div>
  <div>
    {% block content %}{% endblock %}
  </div>

</div> <!-- /container -->
</body>
</html>

learning_log/learning_logs/templates/learning_logs/edit_entry.html
{% extends "learning_logs/base.html" %}
{% block content %}
<!-- 对上传的条目进行更改， -->
<p>
  <a href="{%url 'learning_logs:topic' topic.id%}">{{ topic }}</a>
</p>



<p>Edit entry:</p>
<!-- 跳转到视图函数edit_entry进行重新保存处理 -->
<form action="{%url 'learning_logs:edit_entry' entry.id%}" method='post' enctype="multipart/form-data">

  {%csrf_token%}
  {{ form.as_p}}
  <input type="file" name="img">
  <button name="submit">save changes</button>

</form>
{% endblock content %}

learning_log/learning_logs/templates/learning_logs/index.html
{% extends "learning_logs/base.html" %}
<!-- 所谓的网站起始页，俗称导航页 -->
{% block header %}
  <div class="jumbotron">
    <h2>Hello，欢迎使用超市收银系统！</h2>
  </div>
{% endblock header %}

{% block content %}
  <h3>
    <a href="{% url 'users:register' %}">Register an account </a>
  </h3>
  <h3>

  </h3>
{% endblock content %}

learning_log/learning_logs/templates/learning_logs/new_entry.html
{% extends "learning_logs/base.html" %}
{% block content %}
<!-- 仅仅新建条目：提交文本和图片的时候跳转此页面-->  
 <p>
  <a href="{%url 'learning_logs:topic' topic.id%}">{{ topic }}</a>
  </p>
  <p>Add a new entry:</p>
<!-- 当有图片和条目提交时候，跳转到到视图函数new_entry进行处理 -->
  <form action="{%url 'learning_logs:new_entry' topic.id%}" method='post' enctype="multipart/form-data">
    {% csrf_token %}
    {{ form.as_p }}
  <input type="file" name="img">
  <button name="submit">add entry</button>

<!-- {% csrf_token %}用来防止跨站请求伪造，form.as_p以段落的格式创建所有表格元素。 -->

</form>
{% endblock content %}

learning_log/learning_logs/templates/learning_logs/new_topic.html
{% extends "learning_logs/base.html" %}
{% load bootstrap3 %}
<!-- 该模板用于新建主题（topic），但是需要完善主题相关图片的上传-->
{% block header %}

  <h2>Add a new topic:</h2>

{% endblock header %}


{% block content %}

<!-- 当有主题提交的时候，跳转到视图函数new_topic，进行处理 -->
  <form class="form" action="{% url 'learning_logs:new_topic' %}" method="post">

    {% csrf_token %}

    {% bootstrap_form form %}


    {% buttons %}

      <button class="btn btn-primary" name="submit">add topic</button>

    {% endbuttons %}

  </form>


{% endblock content %}

learning_log/learning_logs/templates/learning_logs/shop.html
<!DOCTYPE html>
{% load staticfiles %}
<html>
<header>


	<title>Shopping Cart</title>
    <meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
	<script type="text/javascript" src="{% static 'js/jquery-1.11.min.js' %}"></script>
	<script type="text/javascript" src="{% static 'js/etao.js' %}"></script>
	<script type="text/javascript" src="{% static 'js/cart.js' %}"></script>
	<link href="{% static 'css/cart.css' %}" media="screen" rel="stylesheet" type="text/css" />
	<link href="{% static 'css/bootstrap.min.css' %}" media="screen" rel="stylesheet" type="text/css" />
	<script type="text/javascript" language="javascript">
           function shop(id) {
               $.getJSON("/data/" + id + "/",function(data) {
                $.each(data, function(){
                <!--其中each是循环的方法，遍历语句-->
                    $("#content").html(this.type);
                });
               });
           }
           function timeDown(limit, i) {
               limit--;
               if (i > 4) {
                   i = 0;
               }
               if (limit < 0) {
                   limit = 3;
                   shop(i);
                   i++;
               }
               $('#time').text(limit + '秒后刷新');
               setTimeout(function() {
                   timeDown(limit, i);
               }, 1000)
           }

           $(document).ready(function() {
               timeDown(3, 0)
        })
    </script>
</header>
<body class="container">
	<div class="row hidden-print">
		<div class="col-lg-12 col-md-12 col-sm-12 col-xs-12">
			<ol class="breadcrumb">
				<li><a href="<%=application.getContextPath()%>">首页</a></li>
                <li class="active">查看购物车</li>
			</ol>
		</div>
	</div>
    <div class="cart-wrap">
		<table id="cartTable" class="cart table table-condensed">
			<thead>
				<tr>
					<td class="t-checkbox "><label><input class="check-all check" type="checkbox"/>全选</label></td>
					<th class="t-goods text-center"><label>产品型号</label></th>
					<th class="text-center">产品备注</th>
					<th class="t-selling-price text-center"><label>销售单价</label></th>
					<th class="t-qty text-center"><label>采购数量</label></th>
					<th class="t-subtotal text-center"><label>金额小计</label></th>
					<th class="t-action"><label>操作</label></th>
				</tr>
			</thead>
			<tbody>
			<!--从此处开始显示第一个商品信息-->
			{% for t in type %}


				<tr>
					<td colspan="2" class="goods"><label> <input type="checkbox" class="check-one check"  /></label ><label >{{ t.type }}</label></td>
					<td class="text-center">无</td>
					<td class="selling-price number small-bold-red text-right"
								style="padding-top: 1.1rem;" data-bind={{ t.money }}>{{ t.money }}</td>
					<td>
						<div class="input-group input-group-sm">
							<span class="input-group-addon minus">-</span> <input
										type="text" class="number form-control input-sm" value= {{ t.number }} >
							<span class="input-group-addon plus">+</span>
						</div>
					</td>
					<td class="subtotal number small-bold-red text-right" style="padding-top: 1.1rem;"></td>
					<td class="action" style="padding-top: 1.1rem;"><span class="delete btn btn-xs btn-warning">删除</span></td>
				</tr>


			{% endfor %}
			<!--从此处第一个商品信息显示结束-->
				<tr>
					<td colspan="2" class="goods"><label><input
									type="checkbox" class="check-one check" />ZB15KQE-TFD-558</label></td>
					<td></td>
					<td class="selling-price number small-bold-red text-right"
								style="padding-top: 1.1rem;" data-bind="1100">1100</td>
					<td>
						<div class="input-group input-group-sm">
							<span class="input-group-addon minus">-</span> <input
										type="text" class="number form-control input-sm" value="3" />
							<span class="input-group-addon plus">+</span>
						</div>
					</td>
					<td class="subtotal number small-bold-red text-right"
								style="padding-top: 1.1rem;"></td>
					<td class="action" style="padding-top: 1.1rem;"><span
								class="delete btn btn-xs btn-warning">删除</span></td>
				</tr>
				<tr>
					<td colspan="2" class="goods"><label><input
									type="checkbox" class="check-one check" />ZB21KQ-TFD-558</label></td>
					<td></td>
					<td class="selling-price number small-bold-red text-right"
								style="padding-top: 1.1rem;" data-bind="1200">1200</td>
					<td>
						<div class="input-group input-group-sm">
							<span class="input-group-addon minus">-</span> <input
										type="text" class="number form-control input-sm" value="6" />
							<span class="input-group-addon plus">+</span>
						</div>
					</td>
					<td class="subtotal number small-bold-red text-right"
								style="padding-top: 1.1rem;"></td>
					<td class="action" style="padding-top: 1.1rem;"><span
								class="delete btn btn-xs btn-warning">删除</span></td>
				</tr>
				<tr>
					<td colspan="2" class="goods"><label><input
									type="checkbox" class="check-one check" />ZBD45KQE-TFD-558</label></td>
					<td></td>
					<td class="selling-price number small-bold-red text-right"
								style="padding-top: 1.1rem;" data-bind="1400">1400</td>
					<td>
						<div class="input-group input-group-sm">
							<span class="input-group-addon minus">-</span> <input
										type="text" class="number form-control input-sm" value="8" />
							<span class="input-group-addon plus">+</span>
						</div>
					</td>
					<td class="subtotal number small-bold-red text-right"></td>
					<td class="action" style="padding-top: 1.1rem;"><span
								class="delete btn btn-xs btn-warning">删除</span></td>
				</tr>
			</tbody>
		</table>

		<div class="row">
			<div class="col-md-12 col-lg-12 col-sm-12">
				<div class="cart-summary">
					<div style="margin-left: 2rem;" class="pull-right">
						<a href="{% url 'learning_logs:confirmation' %}"
							id="btn_settlement" type="button" class="btn btn-primary" >去结算</a>
					</div>
					<div style="margin-left: 1rem; margin-top: 0.4rem;" class="pull-right total">
						<label>金额合计:<span id="priceTotal" class="price-total large-bold-red">0.00</span></label>
					</div>
					<div style="margin-top: 4px;" class="pull-right">
						<label>您选择了<span id="itemCount" class="large-bold-red" style="margin: 0 4px;"></span>种产品型号，共计<span id="qtyCount" class="large-bold-red" style="margin: 0 4px;"></span>件
						</label>
					</div>
				</div>
			</div>
		</div>
	</div>
</body>
</html>

learning_log/learning_logs/templates/learning_logs/topic.html
{% extends "learning_logs/base.html" %}
<!-- 此页面用于各主题对应的条目加载，包括条目涉及的图片加载，图片加载需修改-->
{% block header %}<!-- 此写法实现功能类的，标签 -->

  <h2>{{ topic }}</h2>

{% endblock header %}


{% block content %}

  <p>

    <a href="{% url 'learning_logs:new_entry' topic.id %}">add new entry</a>
	<li>you can insert your picture after your entry .</li>
  </p>


  {% for entry in entries %}

    <div class="panel panel-default">

      <div class="panel-heading">

        <h3>

          {{ entry.date_added|date:"M d, Y H:i" }}

<!-- 当前用户为主题的创建者，则进行给予条目更改特权 -->
          {% if topic.owner == request.user%}
          <small>

            <a href="{% url 'learning_logs:edit_entry' entry.id %}"> edit entry</a>

          </small>
          {% endif %}
        </h3>

      </div>

      <div class="panel-body">

        {{ entry.text|linebreaks }}
		{% for img in imgs %}
		
		{% if entry.date_added|date:"M d, Y H:i" == img.date_added|date:"M d, Y H:i"%}
			<img src="/static/{{ img.img.url }}" alt="subject picture" width="500" height="270"><br/>
		{% endif %}	
		
		{% endfor %}
		
      </div>



    </div> <!-- panel -->

  {% empty %}

    <li>

      There are no entries for this topic yet.

    </li>

  {% endfor %}


{% endblock content %}

learning_log/learning_logs/templates/learning_logs/topics.html
{% extends "learning_logs/base.html" %}
{% load staticfiles %}
<!-- 此页面仅仅用于各主题的显示，及其主题关联的本地静态图片的加载-->
{% block header %}

  <h1>Topics</h1>

{% endblock header %}


{% block content %}


  <ul>

    {% for topic in  topics %}

      <li>

        <h3>

          <a href="{% url 'learning_logs:topic' topic.id %}">{{ topic }}</a>

        </h3>
		
		

		<img  src="/static/images/{{ topic }}.jpg" alt="subject picture" width="320" height="240"/> 
		
		
      </li>

    {% empty %}

      <li>No topics have been added yet.</li>

    {% endfor %}

  </ul>

  <h3><a href="{% url 'learning_logs:new_topic' %}">Add a new topic:</a></h3>


{% endblock content %}

learning_log/learning_logs/templates/learning_logs/vieos_pictures.html
{% extends "learning_logs/base.html" %}
{% block content %}

<p>Add a new topic:</p>
<form action="{%url 'learning_logs:new_topic'%}" method='post'>
  {%csrf_token%}
  {{ form.as_p}}
  <button name="submit">add topic</button>





</form>
{% endblock content %}